#!/usr/bin/env python3
"""Create independent test runs and rebuild Markdown indexes. Python 3.9+ stdlib.

create/update/reindex output JSON; errors return exit code 1. Never rename runs,
modify business repositories, or infer legacy test dates from file timestamps.
"""
from __future__ import annotations
import argparse
from datetime import datetime
import json
from pathlib import Path
import re
import sys
from urllib.parse import quote

STATUSES = ('planned', 'running', 'completed', 'blocked', 'aborted', 'not-required')
REVIEWS = ('not-applicable', 'pending', 'reviewed', 'issues', 'missing-evidence')
TERMINAL = {'completed', 'blocked', 'aborted', 'not-required'}
MARKER = '<!-- Generated by fulllink-test run_records.py -->'


def now():
    return datetime.now().astimezone()


def slug(value):
    text = re.sub(r'[^\w\-\u4e00-\u9fff]+', '-', value.strip(), flags=re.UNICODE).strip('-_')
    if not text or text in ('.', '..'):
        raise ValueError('模块/主题必须包含有效名称')
    return text[:60]


def modules(values):
    result = sorted(set(values))
    if not result or any(v != slug(v) for v in result):
        raise ValueError('模块名须与知识层一致，使用字母数字中文横杠下划线（最长60字符）')
    return result


def cell(value):
    return str(value).replace('|', '\\|').replace('\n', ' ').replace('\r', ' ')


def write_atomic(path, text):
    # Indexed artifacts only; unique temporary file avoids truncating prior files on error.
    import tempfile
    import os
    if path.is_symlink():
        raise ValueError(f'拒绝写入符号链接：{path}')
    with tempfile.NamedTemporaryFile(mode='w', encoding='utf-8', dir=path.parent,
                                     delete=False, prefix='.run-records-', suffix='.tmp') as f:
        temp = Path(f.name)
        f.write(text)
    try:
        os.replace(temp, path)
    finally:
        temp.unlink(missing_ok=True)


def workspace_root(value):
    ws = Path(value).resolve()
    if not (ws / 'workspace.yaml').is_file():
        raise ValueError(f'缺少 workspace.yaml：{ws}；请使用项目测试空间路径')
    return ws


def runs_root(ws):
    root = ws / 'runs'
    if root.is_symlink():
        raise ValueError('runs/ 不得为符号链接')
    root.mkdir(exist_ok=True)
    return root


def validate(data, directory):
    if data.get('runId') != directory.name:
        raise ValueError('runId 与所在目录不一致')
    modules(data['modules'])
    for key in ('startedAt', 'finishedAt'):
        value = data.get(key)
        if value is None and key == 'finishedAt':
            continue
        parsed = datetime.fromisoformat(value)
        if parsed.utcoffset() is None:
            raise ValueError(f'{key} 必须包含时区')
    if data.get('status') not in STATUSES or data.get('humanReview') not in REVIEWS:
        raise ValueError('执行状态或人工核对状态无效')
    if data.get('executionMode') not in ('local', 'existing', 'mixed'):
        raise ValueError('运行方式无效')
    if not isinstance(data.get('environments'), list) or not data['environments']:
        raise ValueError('缺少环境列表')


def artifact(directory, name, base, label):
    p = directory / name
    if not p.exists():
        return f'{label}：未生成'
    import os
    relative = Path(os.path.relpath(p, base))
    return f'[{label}]({quote(relative.as_posix(), safe="/")})'


def index_text(records, base, title, legacy=()):
    lines = [MARKER, f'# {title}', '', '按开始时间倒序；completed 表示执行结束，结论及人工状态单列。', '',
             '| 开始/结束时间 | 模块 | 主题 | 环境/方式 | 状态 | 结论 | 人工核对 | run-id | 产物 |',
             '|---|---|---|---|---|---|---|---|---|']
    for data, directory in records:
        links = ' · '.join(artifact(directory, n, base, label) for n, label in
                           [('plan.md', '计划'), ('report.md', 'Markdown'),
                            ('report.html', 'HTML'), ('videos', '录像'), ('evidence', '证据')])
        values = [f'{data["startedAt"]} / {data.get("finishedAt") or "未结束"}',
                  ', '.join(data['modules']), data.get('topic', ''),
                  f'{", ".join(str(v) for v in data["environments"])} / {data["executionMode"]}',
                  data['status'], data.get('summary', '待执行'), data['humanReview'], data['runId']]
        lines.append('| ' + ' | '.join(cell(v) for v in values) + ' | ' + links + ' |')
    if not records:
        lines += ['', '暂无已登记轮次。']
    if legacy:
        lines += ['', '## 旧记录（元数据未登记或无效）', '',
                  '| 原目录 | 模块/时间 | 说明 | 产物 |', '|---|---|---|---|']
        for directory, reason in legacy:
            links = ' · '.join(artifact(directory, n, base, label) for n, label in
                               [('plan.md', '计划'), ('report.md', 'Markdown'), ('report.html', 'HTML')])
            lines.append(f'| {cell(directory.name)} | 未知 | {cell(reason)} | {links} |')
    return '\n'.join(lines) + '\n'


def reindex(ws):
    root = runs_root(ws)
    records, legacy = [], []
    for directory in root.iterdir():
        if directory.name.startswith('.') or directory.name == 'by-module':
            continue
        if not directory.is_dir() or directory.is_symlink():
            continue
        try:
            data = json.loads((directory / 'run.json').read_text(encoding='utf-8'))
            validate(data, directory)
            records.append((data, directory))
        except (OSError, ValueError, TypeError, KeyError) as exc:
            legacy.append((directory, '缺少 run.json' if not (directory / 'run.json').exists()
                           else f'元数据无效：{exc}'))
    records.sort(key=lambda row: (datetime.fromisoformat(row[0]['startedAt']), row[0]['runId']), reverse=True)
    grouped = root / 'by-module'
    if grouped.is_symlink():
        raise ValueError('by-module/ 不得为符号链接')
    grouped.mkdir(exist_ok=True)
    names = {m for data, _ in records for m in data['modules']}
    # Refresh stale generated module indexes too, leaving user files untouched.
    for path in grouped.glob('*.md'):
        if not path.is_symlink() and path.read_text(encoding='utf-8').startswith(MARKER):
            names.add(path.stem)
    for name in sorted(names):
        target = grouped / f'{name}.md'
        if target.exists() and not target.read_text(encoding='utf-8').startswith(MARKER):
            raise ValueError(f'模块索引位置有用户文件，不覆盖：{target}')
        selected = [(d, p) for d, p in records if name in d['modules']]
        write_atomic(target, index_text(selected, grouped, f'{name} 模块测试记录'))
    write_atomic(root / 'INDEX.md', index_text(records, root, '测试记录总索引', sorted(legacy)))
    return {'index': str(root / 'INDEX.md'), 'moduleIndexDir': str(grouped),
            'runs': len(records), 'legacyRuns': len(legacy)}


def create(args):
    ws = workspace_root(args.workspace)
    root = runs_root(ws)
    ms = modules(args.module)
    topic = args.topic.strip()
    label = ms[0] if len(ms) == 1 else 'cross-module'
    if args.rerun_of and (Path(args.rerun_of).name != args.rerun_of or args.rerun_of in ('.', '..')
                         or not (root / args.rerun_of).is_dir()):
        raise ValueError('rerun-of 必须是当前空间已存在的 run-id')
    for _ in range(10):
        started = now()
        run_id = f'{started:%Y%m%d-%H%M%S-%f}__{label}__{slug(topic)}'
        directory = root / run_id
        try:
            directory.mkdir()
            break
        except FileExistsError:
            continue
    else:
        raise ValueError('无法创建唯一轮次目录，请重试')
    data = {'schemaVersion': 1, 'runId': run_id, 'startedAt': started.isoformat(),
            'finishedAt': None, 'modules': ms, 'topic': topic,
            'environments': list(dict.fromkeys(args.environment)), 'executionMode': args.mode,
            'status': 'planned', 'summary': '待执行', 'humanReview': 'not-applicable',
            'rerunOf': args.rerun_of, 'repositories': [], 'components': [],
            'counts': {name: None for name in ('PASS', 'FAIL', 'BLOCKED', 'MANUAL', 'SKIPPED-降级')}}
    write_atomic(directory / 'run.json', json.dumps(data, ensure_ascii=False, indent=2) + '\n')
    return {'runId': run_id, 'runDir': str(directory), **reindex(ws)}


def update(args):
    original = Path(args.run_dir).absolute()
    directory = original.resolve()
    ws = workspace_root(directory.parent.parent)
    root = runs_root(ws)
    if original.is_symlink() or directory.parent != root or directory.name == 'by-module':
        raise ValueError('run-dir 必须为 runs/ 下实际轮次目录')
    data = json.loads((directory / 'run.json').read_text(encoding='utf-8'))
    validate(data, directory)
    if args.module:
        data['modules'] = modules(args.module)
    if args.summary is not None:
        data['summary'] = args.summary
    if args.human_review:
        data['humanReview'] = args.human_review
    if args.status:
        if data['status'] in TERMINAL and args.status not in TERMINAL:
            raise ValueError('已结束轮次不重新执行，请创建新 run-id')
        data['status'] = args.status
        if args.status in TERMINAL and not data.get('finishedAt'):
            data['finishedAt'] = now().isoformat()
    validate(data, directory)
    write_atomic(directory / 'run.json', json.dumps(data, ensure_ascii=False, indent=2) + '\n')
    return {'runId': data['runId'], 'runDir': str(directory), **reindex(ws)}


def main(argv=None):
    parser = argparse.ArgumentParser(description='测试轮次创建、状态更新与历史索引')
    commands = parser.add_subparsers(dest='command', required=True)
    c = commands.add_parser('create')
    c.add_argument('--workspace', required=True)
    c.add_argument('--module', action='append', required=True)
    c.add_argument('--topic', required=True)
    c.add_argument('--environment', action='append', required=True)
    c.add_argument('--mode', choices=('local', 'existing', 'mixed'), required=True)
    c.add_argument('--rerun-of')
    u = commands.add_parser('update')
    u.add_argument('--run-dir', required=True)
    u.add_argument('--module', action='append')
    u.add_argument('--status', choices=STATUSES)
    u.add_argument('--summary')
    u.add_argument('--human-review', choices=REVIEWS)
    ix = commands.add_parser('reindex')
    ix.add_argument('--workspace', required=True)
    args = parser.parse_args(argv)
    try:
        if args.command == 'create':
            data = create(args)
        elif args.command == 'update':
            data = update(args)
        else:
            data = reindex(workspace_root(args.workspace))
        print(json.dumps({'status': 'ok', 'data': data}, ensure_ascii=False, indent=2))
        return 0
    except (OSError, ValueError, TypeError, KeyError) as exc:
        print(json.dumps({'status': 'error', 'error': {'message': str(exc),
                         'action': '检查空间路径、轮次元数据和参数后重试；不覆盖旧记录'}}, ensure_ascii=False))
        return 1


if __name__ == '__main__':
    sys.exit(main())
